# Generated by Django 4.2.1 on 2023-05-30 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_registered",
        ),
    ]
